import { useEffect, useRef, useState } from "react";
import { Html5Qrcode } from "html5-qrcode";
import { createAttendance } from "../../services/attendanceService";

const AttendanceQRScanner = ({ courseId, batchId, date, onSuccess }) => {
  const scannerRef = useRef(null);
  const busyRef = useRef(false);

  const [scanning, setScanning] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const stopScanner = async () => {
    const scanner = scannerRef.current;
    if (!scanner) return;

    try {
      if (scanner.isScanning) {
        await scanner.stop();
      }
    } catch (err) {
      console.warn("Scanner stop:", err);
    }

    try {
      scanner.clear();
    } catch {
      // Scanner may already be cleared.
    }

    scannerRef.current = null;
    setScanning(false);
  };

  useEffect(() => {
    return () => {
      const scanner = scannerRef.current;

      if (scanner) {
        if (scanner.isScanning) {
          scanner.stop()
            .then(() => scanner.clear())
            .catch(() => {});
        } else {
          try {
            scanner.clear();
          } catch {
            // Already cleared.
          }
        }

        scannerRef.current = null;
      }
    };
  }, []);

  const startScanner = async () => {
    if (!courseId || !batchId || !date) {
      setError("Select a course, batch, and date first.");
      return;
    }

    setError("");
    setMessage("");

    try {
      const scanner = new Html5Qrcode("attendance-qr-reader");
      scannerRef.current = scanner;

      await scanner.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 250, height: 250 } },
        async (decodedText) => {
          if (busyRef.current) return;

          console.log("QR DETECTED:", decodedText);
          setMessage(`QR detected: ${decodedText}`);

          // QR codes generated by EMS use this format:
          // EMS-STUDENT:<MongoDB student ID>
          const match = decodedText.trim().match(
            /^EMS-STUDENT:([a-f\d]{24})$/i
          );

          if (!match) {
            setError("Invalid EMS student QR code.");
            return;
          }

          busyRef.current = true;
          setError("");
          setMessage("QR detected. Recording attendance...");

          try {
            await createAttendance({
              student_id: match[1],
              course_id: courseId,
              batch_id: batchId,
              attendance_date: date,
              status: "Present",
              remarks: "Recorded by QR scan",
            });

            setMessage("Attendance recorded successfully.");
            await stopScanner();
            await onSuccess?.();
          } catch (err) {
            const status = err?.response?.status;
            setError(
              status === 409
                ? "Attendance has already been recorded for this student today."
                : err?.response?.data?.message ||
                    "Could not record attendance. Verify the student and selected batch."
            );
            setMessage("");
          } finally {
            busyRef.current = false;
          }
        },
        () => {
          // Ignore ordinary frames without a QR code.
        }
      );

      setScanning(true);
    } catch (err) {
      scannerRef.current = null;
      setScanning(false);
      setError(
        "Could not start the camera. Allow camera permission and try again."
      );
    }
  };

  return (
    <section className="attendance-card attendance-qr-card">
      <div className="attendance-qr-heading">
        <div>
          <h2>QR Attendance Scanner</h2>
          <p>
            Scan an EMS student QR code to record attendance for the
            selected course, batch, and date.
          </p>
        </div>

        {!scanning ? (
          <button
            type="button"
            className="attendance-primary-button"
            onClick={startScanner}
          >
            Start Scanner
          </button>
        ) : (
          <button
            type="button"
            className="attendance-secondary-button"
            onClick={stopScanner}
          >
            Stop Scanner
          </button>
        )}
      </div>

      <div
        id="attendance-qr-reader"
        className="attendance-qr-reader"
      />

      {error && <div className="attendance-error">{error}</div>}
      {message && <div className="attendance-success">{message}</div>}

      <p className="attendance-qr-note">
        Keep the camera pointed at the student's official EMS QR code.
        Duplicate attendance is rejected by the backend.
      </p>
    </section>
  );
};

export default AttendanceQRScanner;
